#include "stdafx.h"
#include "olegdi+.h"

int GetPackVersion(char* Source){
	int x=3;
	LPCSTR ext= PathFindExtension(Source);
	MessageBox(0,ext,0,0);
	if (strcmp(strlwr((char*)ext),".pwe")==0)x= 1;
	if (strcmp(strlwr((char*)ext),".")==0)x= 2;
	if (strcmp(strlwr((char*)ext),".cvt")==0)x= 3;
	return x;
}
void initTransfoDatas(){
	GetCurrentDirectory(256,TransfoDatas2.appPath);
	wsprintf(TransfoDatas2.RapportPath,"%s\\Datas\\Transfo\\Rapports\\",TransfoDatas2.appPath);
	wsprintf(TransfoDatas2.ArchivePath,"%s\\Datas\\Transfo\\Archives\\",TransfoDatas2.appPath);
	wsprintf(TransfoDatas2.ReferentielFileName,"%s\\Datas\\Transformateurs.ref",TransfoDatas2.appPath);
}

char* ReadDatas(char* Section, char* Clef, char* Source){	char tmp[260];	GetPrivateProfileString(Section,Clef,"?",tmp,260,Source);	return 	tmp;}
int SetDefautVersion(char* Source){	return UpdateDatas("DATAS","Version","3",Source);}
int UpdateDatas(char* Section, char* Clef, char* Valeur, char* Cible){	return WritePrivateProfileString(Section,Clef,Valeur,Cible)	;}
int UpdateDatas(char* Section, char* Clef, double Valeur, char* Cible){	char tmp[80]; wsprintf(tmp,"%f",Valeur);return WritePrivateProfileString(Section,Clef,tmp,Cible)	;}
int SaveData(TTransfoDatasV2 datas, char* Cible){
	UpdateDatas("STICKER", "V1",datas.tableau.VoltageV1, Cible);
	UpdateDatas("STICKER", "V2",datas.tableau.VoltageV2, Cible);
	UpdateDatas("STICKER", "V3",datas.tableau.VoltageV3, Cible);
	UpdateDatas("STICKER", "V4",datas.tableau.VoltageV4, Cible);
	UpdateDatas("STICKER", "V5",datas.tableau.VoltageV5, Cible);
	UpdateDatas("STICKER", "PC1",datas.tableau.PCent1, Cible);
	UpdateDatas("STICKER", "PC2",datas.tableau.PCent2, Cible);
	UpdateDatas("STICKER", "PC3",datas.tableau.PCent3, Cible);
	UpdateDatas("STICKER", "PC4",datas.tableau.PCent4, Cible);
	UpdateDatas("STICKER", "PC5",datas.tableau.PCent5, Cible);
	UpdateDatas("TAB1", "VoltageV1",datas.tableau.VoltageV1, Cible);
	UpdateDatas("TAB1", "VoltageV2",datas.tableau.VoltageV2, Cible);
	UpdateDatas("TAB1", "VoltageV3",datas.tableau.VoltageV3, Cible);
	UpdateDatas("TAB1", "VoltageV4",datas.tableau.VoltageV4, Cible);
	UpdateDatas("TAB1", "VoltageV5",datas.tableau.VoltageV5, Cible);
	UpdateDatas("TAB1", "CoefV1",datas.tableau.t1.CoefV1, Cible);
	UpdateDatas("TAB1", "CoefV2",datas.tableau.t1.CoefV2, Cible);
	UpdateDatas("TAB1", "CoefV3",datas.tableau.t1.CoefV3, Cible);
	UpdateDatas("TAB1", "CoefV4",datas.tableau.t1.CoefV4, Cible);
	UpdateDatas("TAB1", "CoefV5",datas.tableau.t1.CoefV5, Cible);
	UpdateDatas("TAB1", "RatioV1",datas.tableau.t1.RatioV1, Cible);
	UpdateDatas("TAB1", "RatioV2",datas.tableau.t1.RatioV2, Cible);
	UpdateDatas("TAB1", "RatioV3",datas.tableau.t1.RatioV3, Cible);
	UpdateDatas("TAB1", "RatioV4",datas.tableau.t1.RatioV4, Cible);
	UpdateDatas("TAB1", "RatioV5",datas.tableau.t1.RatioV5, Cible);
	UpdateDatas("TAB1", "AmpV1",datas.tableau.t1.AmpV1, Cible);
	UpdateDatas("TAB1", "AmpV2",datas.tableau.t1.AmpV2, Cible);
	UpdateDatas("TAB1", "AmpV3",datas.tableau.t1.AmpV3, Cible);
	UpdateDatas("TAB1", "AmpV4",datas.tableau.t1.AmpV4, Cible);
	UpdateDatas("TAB1", "AmpV5",datas.tableau.t1.AmpV5, Cible);
	UpdateDatas("TAB2", "VoltageV1",datas.tableau.VoltageV1, Cible);
	UpdateDatas("TAB2", "VoltageV2",datas.tableau.VoltageV2, Cible);
	UpdateDatas("TAB2", "VoltageV3",datas.tableau.VoltageV3, Cible);
	UpdateDatas("TAB2", "VoltageV4",datas.tableau.VoltageV4, Cible);
	UpdateDatas("TAB2", "VoltageV5",datas.tableau.VoltageV5, Cible);
	UpdateDatas("TAB2", "CoefV1",datas.tableau.t2.CoefV1, Cible);
	UpdateDatas("TAB2", "CoefV2",datas.tableau.t2.CoefV2, Cible);
	UpdateDatas("TAB2", "CoefV3",datas.tableau.t2.CoefV3, Cible);
	UpdateDatas("TAB2", "CoefV4",datas.tableau.t2.CoefV4, Cible);
	UpdateDatas("TAB2", "CoefV5",datas.tableau.t2.CoefV5, Cible);
	UpdateDatas("TAB2", "RatioV1",datas.tableau.t2.RatioV1, Cible);
	UpdateDatas("TAB2", "RatioV2",datas.tableau.t2.RatioV2, Cible);
	UpdateDatas("TAB2", "RatioV3",datas.tableau.t2.RatioV3, Cible);
	UpdateDatas("TAB2", "RatioV4",datas.tableau.t2.RatioV4, Cible);
	UpdateDatas("TAB2", "RatioV5",datas.tableau.t2.RatioV5, Cible);
	UpdateDatas("TAB2", "AmpV1",datas.tableau.t2.AmpV1, Cible);
	UpdateDatas("TAB2", "AmpV2",datas.tableau.t2.AmpV2, Cible);
	UpdateDatas("TAB2", "AmpV3",datas.tableau.t2.AmpV3, Cible);
	UpdateDatas("TAB2", "AmpV4",datas.tableau.t2.AmpV4, Cible);
	UpdateDatas("TAB2", "AmpV5",datas.tableau.t2.AmpV5, Cible);
	UpdateDatas("TAB3", "VoltageV1",datas.tableau.VoltageV1, Cible);
	UpdateDatas("TAB3", "VoltageV2",datas.tableau.VoltageV2, Cible);
	UpdateDatas("TAB3", "VoltageV3",datas.tableau.VoltageV3, Cible);
	UpdateDatas("TAB3", "VoltageV4",datas.tableau.VoltageV4, Cible);
	UpdateDatas("TAB3", "VoltageV5",datas.tableau.VoltageV5, Cible);
	UpdateDatas("TAB3", "CoefV1",datas.tableau.t3.CoefV1, Cible);
	UpdateDatas("TAB3", "CoefV2",datas.tableau.t3.CoefV2, Cible);
	UpdateDatas("TAB3", "CoefV3",datas.tableau.t3.CoefV3, Cible);
	UpdateDatas("TAB3", "CoefV4",datas.tableau.t3.CoefV4, Cible);
	UpdateDatas("TAB3", "CoefV5",datas.tableau.t3.CoefV5, Cible);
	UpdateDatas("TAB3", "RatioV1",datas.tableau.t3.RatioV1, Cible);
	UpdateDatas("TAB3", "RatioV2",datas.tableau.t3.RatioV2, Cible);
	UpdateDatas("TAB3", "RatioV3",datas.tableau.t3.RatioV3, Cible);
	UpdateDatas("TAB3", "RatioV4",datas.tableau.t3.RatioV4, Cible);
	UpdateDatas("TAB3", "RatioV5",datas.tableau.t3.RatioV5, Cible);
	UpdateDatas("TAB3", "AmpV1",datas.tableau.t3.AmpV1, Cible);
	UpdateDatas("TAB3", "AmpV2",datas.tableau.t3.AmpV2, Cible);
	UpdateDatas("TAB3", "AmpV3",datas.tableau.t3.AmpV3, Cible);
	UpdateDatas("TAB3", "AmpV4",datas.tableau.t3.AmpV4, Cible);
	UpdateDatas("TAB3", "AmpV5",datas.tableau.t3.AmpV5, Cible);
	UpdateDatas("ID", "Hauteur",datas.id.dimH, Cible);
	UpdateDatas("ID", "Largeur",datas.id.dimD, Cible);
	UpdateDatas("ID", "Profondeur",datas.id.dimV, Cible);
	UpdateDatas("ID", "VolHuile",datas.id.VolHuile, Cible);
	UpdateDatas("ID", "Reference",datas.id.Reference, Cible);
	UpdateDatas("ID", "Numero",datas.id.Numero, Cible);
	UpdateDatas("ID", "Primaire",datas.id.Primaire, Cible);
	UpdateDatas("ID", "Secondaire1",datas.id.Secondaire1, Cible);
	UpdateDatas("ID", "Secondaire2",datas.id.Secondaire2, Cible);
	UpdateDatas("ID", "Secondaire3",datas.id.Secondaire3, Cible);
	UpdateDatas("ID", "Capacite",datas.id.Capacite, Cible);
	UpdateDatas("ID", "Fabriquant",datas.id.Fabriquant, Cible);
	UpdateDatas("ID", "Localisation",datas.id.Localisation, Cible);
	UpdateDatas("ID", "Lot",datas.id.Lot, Cible);
	UpdateDatas("ID", "RecuLe",datas.id.RecuLe, Cible);
	UpdateDatas("ID", "Modele",datas.id.Modele, Cible);
	UpdateDatas("ID", "Phases",datas.id.Phases, Cible);
	UpdateDatas("ID", "Frequence",datas.id.Frequence, Cible);
	UpdateDatas("ID", "LUG",datas.id.LUG, Cible);
	UpdateDatas("ID", "Ratio1",datas.id.Ratio1, Cible);
	UpdateDatas("ID", "Ratio2",datas.id.Ratio2, Cible);
	UpdateDatas("ID", "Ratio3",datas.id.Ratio3, Cible);
	UpdateDatas("ID", "Serial",datas.id.Serial, Cible);
	UpdateDatas("ID", "Poids",datas.id.Poids, Cible);
	UpdateDatas("ID", "Designaton",datas.Designaton, Cible);
	UpdateDatas("ID", "Etat", datas.Etat, Cible);
	UpdateDatas("ID", "Teste",datas.Teste, Cible);
	UpdateDatas("TEST", "IsolementLN",datas.tst.IsolementLN, Cible);
	UpdateDatas("TEST", "IsolementLL",datas.tst.IsolementLL, Cible);
	UpdateDatas("TEST", "IsolemenTN",datas.tst.IsolemenTN, Cible);
	UpdateDatas("TEST", "IsolementLT",datas.tst.IsolementLT, Cible);
	UpdateDatas("TEST", "IsolateurPrimaireExterne",datas.tst.IsolateurPrimaireExterne, Cible);
	UpdateDatas("TEST", "IsolateurPrimaire",datas.tst.IsolateurPrimaire, Cible);
	UpdateDatas("TEST", "IsolateurSecondaire",datas.tst.IsolateurSecondaire, Cible);
	UpdateDatas("TEST", "HumiditePresente",datas.tst.HumiditePresente, Cible);
	UpdateDatas("TEST", "RefroissementEtanche",datas.tst.RefroissementEtanche, Cible);
	UpdateDatas("TEST", "HuileRefroidissement",datas.tst.HuileRefroidissement, Cible);
	UpdateDatas("TEST", "ImpedancePrimaire",datas.tst.ImpedancePrimaire, Cible);
	UpdateDatas("TEST", "ImpedanceSecondaire",datas.tst.ImpedanceSecondaire, Cible);
	UpdateDatas("TEST", "TensionPrimaire",datas.tst.TensionPrimaire, Cible);
	UpdateDatas("TEST", "TensionSecondaire1",datas.tst.TensionSecondaire1, Cible);
	UpdateDatas("TEST", "TensionSecondaire2",datas.tst.TensionSecondaire2, Cible);
	UpdateDatas("TEST", "TensionSecondaire3",datas.tst.TensionSecondaire3, Cible);
	UpdateDatas("TEST", "Fixations",datas.tst.Fixations, Cible);
	UpdateDatas("TEST", "Supports",datas.tst.Supports, Cible);
	UpdateDatas("TEST", "Etancheite",datas.tst.Etancheite, Cible);
	UpdateDatas("TEST", "Peinture",datas.tst.Peinture, Cible);
	UpdateDatas("TEST", "QualiteHuile",datas.tst.QualiteHuile, Cible);
	UpdateDatas("TEST", "Selecteur",datas.tst.Selecteur, Cible);
	UpdateDatas("TEST", "Borne2Terre",datas.tst.Borne2Terre, Cible);
	UpdateDatas("TEST", "ConnecteursSecondaire",datas.tst.ConnecteursSecondaire, Cible);
	UpdateDatas("TEST", "ConexionBobinage",datas.tst.ConexionBobinage, Cible);
	UpdateDatas("TEST", "MultiTension",datas.tst.MultiTension, Cible);
	UpdateDatas("TEST", "Commentaire",datas.tst.Commentaire, Cible);
	UpdateDatas("TEST", "InductanceSecondaire",datas.tst.InductanceSecondaire, Cible);
	return SetDefautVersion(Cible);
}

int CreerRapportText(char* Cible, TTransfoDatasV2 datas){
    FILE* f;
	f=fopen ("myfile.txt","w");
	fprintf(f, "%s\n\n",datas.Designaton );
    fprintf(f, "Testé du %s\n",datas.Teste);
    fprintf(f, "Numéro = %f",datas.id.Numero);
    fprintf(f, "Statut = %s\n",datas.Etat);
    fprintf(f, "Identification \n");
    fprintf(f, "   + Fabricant = %s\n",datas.id.Fabriquant);
    fprintf(f, "   + Modèle = %s\n",datas.id.Modele);
    fprintf(f, "   + Dimensions = %dx%f\n",datas.id.dimD, datas.id.dimH);
    fprintf(f, "   + Lot =%s\n",datas.id.Lot);
    fprintf(f, "   + Recu Le = %s\n",datas.id.RecuLe);
    fprintf(f, "   + Poids = %f Kg",datas.id.Poids);
    fprintf(f, "   + Serial= %s\n",datas.id.Serial);
    fprintf(f, "   + Volume d'huile = %dL|n",datas.id.dimV);
    fprintf(f, "   + Tension Primaire = %dV\n",datas.id.Primaire);
    fprintf(f, "   + Tension Secondaire 1 = %dV\n",datas.id.Secondaire1);
    fprintf(f, "   + Tension Secondaire 2 = %dV\n",datas.id.Secondaire2);
    fprintf(f, "   + Tension Secondaire 3 = %dV\n",datas.id.Secondaire3);
    fprintf(f, "   + Capacitée  %dKVA\n",datas.id.Capacite);
    fprintf(f, "   + Phases = %f\n",datas.id.Phases);
    fprintf(f, "   + Fréquence = %dHz\n",datas.id.Frequence);
    fprintf(f, "   + LUG = %s\n",datas.id.LUG);
    fprintf(f, "   + Ratio %f pour %dV\n",datas.id.Ratio1,datas.id.Secondaire1);
    fprintf(f, "   + Ratio %f pour %dV\n",datas.id.Ratio2,datas.id.Secondaire2);
    fprintf(f, "   + Ratio %f pour %dV\n",datas.id.Ratio3,datas.id.Secondaire3);
    fprintf(f, "   + Reference = %s\n",datas.id.Reference);
    fprintf(f, "   + Localisation = %s\n",datas.id.Localisation);
    fprintf(f, "   + TAB %fV\n",datas.id.Secondaire1);
    fprintf(f, "     + A/1=%f,%f,%f,%f\n",datas.tableau.VoltageV1,datas.tableau.t1.CoefV1,datas.tableau.t1.AmpV1,datas.tableau.t1.RatioV1);
    fprintf(f, "     + B/2=%f,%f,%f,%f\n",datas.tableau.VoltageV2,datas.tableau.t1.CoefV2,datas.tableau.t1.AmpV2,datas.tableau.t1.RatioV2);
    fprintf(f, "     + C/3=%f,%f,%f,%f\n",datas.tableau.VoltageV3,datas.tableau.t1.CoefV3,datas.tableau.t1.AmpV3,datas.tableau.t1.RatioV3);
    fprintf(f, "     + D/4=%f,%f,%f,%f\n",datas.tableau.VoltageV4,datas.tableau.t1.CoefV4,datas.tableau.t1.AmpV4,datas.tableau.t1.RatioV4);
    fprintf(f, "     + E/5=%f,%f,%f,%f\n",datas.tableau.VoltageV5,datas.tableau.t1.CoefV5,datas.tableau.t1.AmpV5,datas.tableau.t1.RatioV5);
    fprintf(f, "   + TAB %fV\n",datas.id.Secondaire2);
    fprintf(f, "     + A/1=%f,%f,%f,%f\n",datas.tableau.VoltageV1,datas.tableau.t2.CoefV1,datas.tableau.t2.AmpV1,datas.tableau.t2.RatioV1);
    fprintf(f, "     + B/2=%f,%f,%f,%f\n",datas.tableau.VoltageV2,datas.tableau.t2.CoefV2,datas.tableau.t2.AmpV2,datas.tableau.t2.RatioV2);
    fprintf(f, "     + C/3=%f,%f,%f,%f\n",datas.tableau.VoltageV3,datas.tableau.t2.CoefV3,datas.tableau.t2.AmpV3,datas.tableau.t2.RatioV3);
    fprintf(f, "     + D/4=%f,%f,%f,%f\n",datas.tableau.VoltageV4,datas.tableau.t2.CoefV4,datas.tableau.t2.AmpV4,datas.tableau.t2.RatioV4);
    fprintf(f, "     + E/5=%f,%f,%f,%f\n",datas.tableau.VoltageV5,datas.tableau.t2.CoefV5,datas.tableau.t2.AmpV5,datas.tableau.t2.RatioV5);
    fprintf(f, "   + TAB %fV\n",datas.id.Secondaire3);
    fprintf(f, "     + A/1=%f,%f,%f,%f\n",datas.tableau.VoltageV1,datas.tableau.t3.CoefV1,datas.tableau.t3.AmpV1,datas.tableau.t3.RatioV1);
    fprintf(f, "     + B/2=%f,%f,%f,%f\n",datas.tableau.VoltageV2,datas.tableau.t3.CoefV2,datas.tableau.t3.AmpV2,datas.tableau.t3.RatioV2);
    fprintf(f, "     + C/3=%f,%f,%f,%f\n",datas.tableau.VoltageV3,datas.tableau.t3.CoefV3,datas.tableau.t3.AmpV3,datas.tableau.t3.RatioV3);
    fprintf(f, "     + D/4=%f,%f,%f,%f\n",datas.tableau.VoltageV4,datas.tableau.t3.CoefV4,datas.tableau.t3.AmpV4,datas.tableau.t3.RatioV4);
    fprintf(f, "     + E/5=%f,%f,%f,%f\n",datas.tableau.VoltageV5,datas.tableau.t3.CoefV5,datas.tableau.t3.AmpV5,datas.tableau.t3.RatioV5);
    fprintf(f, "  + Tests\n");
    fprintf(f, "    + Huile de refroidissement =%f\n",datas.tst.HuileRefroidissement);
    fprintf(f, "    + Isolement Phase/Neutre =%f\n",datas.tst.IsolementLN);
    fprintf(f, "    + Isolement Terre/Neutre =%f\n",datas.tst.IsolemenTN);
    fprintf(f, "    + Isolement Phase/Terre =%f\n",datas.tst.IsolementLT);
    fprintf(f, "    + Isolement Phases/Phases =%f\n",datas.tst.IsolementLL);
	fprintf(f, "    + Isolateur Primaire Externe =%f\n",datas.tst.IsolateurPrimaireExterne);
    fprintf(f, "    + Isolateur Primaire =%f\n",datas.tst.IsolateurPrimaire);
    fprintf(f, "    + Isolateur Secondaire =%f\n",datas.tst.IsolateurSecondaire);
    fprintf(f, "    + Humidite Présente =%f\n",datas.tst.HumiditePresente);
    fprintf(f, "    + Couvercle étanche =%f\n",datas.tst.RefroissementEtanche);
    fprintf(f, "    + Tension Primaire =%f\n",datas.tst.TensionPrimaire);
    fprintf(f, "    + Tension Secondaire 1 =%f\n",datas.tst.TensionSecondaire1);
    fprintf(f, "    + Tension Secondaire 2 =%f\n",datas.tst.TensionSecondaire2);
    fprintf(f, "    + Tension Secondaire 3 =%f\n",datas.tst.TensionSecondaire3);
    fprintf(f, "    + Impédance enroulement primaire %f\n", datas.tst.ImpedancePrimaire);
    fprintf(f, "    + Impédance enroulement secondaire %f\n", datas.tst.ImpedanceSecondaire);
    fprintf(f, "    + Fixations =%f\n",datas.tst.Fixations);
    fprintf(f, "    + Supports =%f\n",datas.tst.Supports);
    fprintf(f, "    + Etancheite =%f\n",datas.tst.Etancheite);
    fprintf(f, "    + Peinture =%f\n",datas.tst.Peinture);
    fprintf(f, "    + QualiteHuile =%f\n",datas.tst.QualiteHuile);
    fprintf(f, "    + Selecteur =%f\n",datas.tst.Selecteur);
    fprintf(f, "    + Borne2Terre =%f\n",datas.tst.Borne2Terre);
    fprintf(f, "    + MultiTension =%f\n",datas.tst.MultiTension);
    fprintf(f, "    + Connecteur Secondaire =%f\n",datas.tst.ConnecteursSecondaire);
    fprintf(f, "    + Conexion Bobinage =%f\n",datas.tst.ConexionBobinage);
	return fclose(f);
}
